from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from open_composer.config import ensure_dir, project_root
from open_composer.models.strategy_spec import StrategySpec, load_strategy_spec
from open_composer.storage import append_jsonl, write_json


@dataclass(frozen=True)
class ShortRiskReportResult:
    strategy_name: str
    report_path: Path
    source_cards_path: Path
    borrow_cost_path: Path
    squeeze_stress_path: Path
    dividend_risk_path: Path
    exposure_policy_path: Path
    status: str


def build_short_risk_report(spec_path: Path, root: Path | None = None) -> ShortRiskReportResult:
    base = root or project_root()
    spec = load_strategy_spec(spec_path)
    if spec.position_direction == "long_only":
        raise ValueError("short-risk report is only applicable to short_only or long_short specs")
    source_cards_path = base / "reports" / "harness" / "source_cards" / f"{spec.name}.jsonl"
    borrow_cost_path = base / "reports" / "research" / f"{spec.name}-borrow-cost-estimate.json"
    squeeze_stress_path = base / "reports" / "research" / f"{spec.name}-short-squeeze-stress.json"
    dividend_risk_path = base / "reports" / "research" / f"{spec.name}-ex-dividend-risk-note.md"
    exposure_policy_path = (
        base / "reports" / "harness" / "execution" / f"{spec.name}-short-exposure-policy.json"
    )
    report_path = base / "reports" / "research" / f"{spec.name}-short-risk.md"

    append_jsonl(source_cards_path, [_source_card(spec)])
    write_json(borrow_cost_path, _borrow_cost(spec))
    write_json(squeeze_stress_path, _squeeze_stress(spec))
    _write_dividend_note(dividend_risk_path, spec)
    write_json(exposure_policy_path, _exposure_policy(spec))
    _write_report(
        report_path,
        spec,
        source_cards_path,
        borrow_cost_path,
        squeeze_stress_path,
        dividend_risk_path,
        exposure_policy_path,
    )
    return ShortRiskReportResult(
        strategy_name=spec.name,
        report_path=report_path,
        source_cards_path=source_cards_path,
        borrow_cost_path=borrow_cost_path,
        squeeze_stress_path=squeeze_stress_path,
        dividend_risk_path=dividend_risk_path,
        exposure_policy_path=exposure_policy_path,
        status="ok",
    )


def _source_card(spec: StrategySpec) -> dict[str, object]:
    return {
        "claim_id": f"{spec.name}:short-paper-broker-verification-required",
        "claim": (
            "Short-selling paper execution requires broker-specific current evidence for "
            "shortable status, borrow availability, order side semantics, and account rules."
        ),
        "source_url": "https://docs.alpaca.markets/",
        "source_type": "broker_official_docs",
        "accessed_at": "1970-01-01",
        "applies_to": [spec.name, "short_selling"],
        "impact_on_spec": "blocks order_authorized until refreshed with current broker docs",
        "limitations": [
            "placeholder source card generated by local report command",
            "refresh with current official broker pages before paper_auto authorization",
        ],
    }


def _borrow_cost(spec: StrategySpec) -> dict[str, object]:
    return {
        "strategy_name": spec.name,
        "position_direction": spec.position_direction,
        "status": "research_only",
        "borrow_rate_assumption_annual_pct": None,
        "locate_required": True,
        "shortable_field_required": True,
        "notes": [
            "Borrow availability and rate are not inferred from OHLCV.",
            "Paper readiness requires broker source cards and runtime shortable evidence.",
        ],
    }


def _squeeze_stress(spec: StrategySpec) -> dict[str, object]:
    max_position = spec.risk.max_position_weight
    scenarios = [
        {"name": "gap_up_5pct", "gap_pct": 5.0, "loss_pct_of_equity": max_position * 5.0},
        {"name": "gap_up_15pct", "gap_pct": 15.0, "loss_pct_of_equity": max_position * 15.0},
        {"name": "gap_up_30pct", "gap_pct": 30.0, "loss_pct_of_equity": max_position * 30.0},
    ]
    return {
        "strategy_name": spec.name,
        "status": "ok",
        "max_position_weight": max_position,
        "scenarios": scenarios,
        "kill_switch_recommendation": "block new short entries after severe gap or borrow recall",
    }


def _exposure_policy(spec: StrategySpec) -> dict[str, object]:
    return {
        "strategy_name": spec.name,
        "position_direction": spec.position_direction,
        "max_gross_short_exposure": spec.risk.max_position_weight,
        "max_single_name_short_weight": spec.risk.max_position_weight,
        "paper_auto_default": "blocked",
        "requires": [
            "current broker shortability source card",
            "borrow availability or shortable field evidence",
            "ex-dividend risk review",
            "squeeze stress review",
        ],
    }


def _write_dividend_note(path: Path, spec: StrategySpec) -> None:
    ensure_dir(path.parent)
    path.write_text(
        "\n".join(
            [
                f"# Ex-Dividend Risk Note: {spec.name}",
                "",
                "- Short positions may owe dividends and may be affected by corporate actions.",
                "- This note is research evidence only until current broker and symbol-specific",
                "  dividend handling is verified in source cards.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def _write_report(
    path: Path,
    spec: StrategySpec,
    source_cards_path: Path,
    borrow_cost_path: Path,
    squeeze_stress_path: Path,
    dividend_risk_path: Path,
    exposure_policy_path: Path,
) -> None:
    ensure_dir(path.parent)
    path.write_text(
        "\n".join(
            [
                f"# Short Risk Report: {spec.name}",
                "",
                f"- Position direction: `{spec.position_direction}`",
                "- Paper order authorization: `blocked` until broker evidence is current.",
                f"- Source cards: `{source_cards_path}`",
                f"- Borrow cost estimate: `{borrow_cost_path}`",
                f"- Squeeze stress: `{squeeze_stress_path}`",
                f"- Ex-dividend risk: `{dividend_risk_path}`",
                f"- Exposure policy: `{exposure_policy_path}`",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
